#!/bin/sh

#rm -f tmpx
#for v in `cat unixport/lspboots unixport/cmpboots` ;
#do echo "/$v.[chd]/d" >>tmpx
#done
HERE=$1
echo > ${HERE}/tmpx
GCL=`basename ${HERE}`
GCL_VERS=$2
OBJS=`find ./${GCL} -type f -a -print  | sed  -f ${HERE}/tmpx -e "s:/${GCL}/:/${GCL_VERS}/:g" -e "/~/d" -e "/#/d" -e "/.*\.o/d"   -e "/.*TAGS/d"  -e "/standard-gcl/d" -e "/core/d" -e "/saved_/d" -e "/raw/d"  -e "/rsym$/d" -e "/merge$/d" -e "/dpp$/d" -e "/-$/d" -e "/installed_gcl/d"    -e "/config\.h/d" -e "/_aos/d" -e  "/gazonk/d" -e "/\.out/d"  -e "/print_doc$/d"  -e "/foo/d" -e "/gcllib/d" -e "/\.fn/d" -e "/collectfn.[cdh]/d" -e "/Vmakefile/d" -e "/ps2_/d"  -e "/.*\.a$/d"   -e "/test\//d" -e "/tmpx/d" -e "/makedefs/d" `  
rm -f ${HERE}/tmpx

echo ${OBJS}






